version: '3'
services:
    web-server:
        build: .
        ports:
            - 8080:80
            - 6060:6060
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock # ZU TESTZWECKEN AUF VM
    database:
        build:
            context: ./db_init
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: users
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 1201:3306