version: '3'
services:
    web-server:
        build: .
        ports:
            - 8080:80
            - 6060:6060
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock # NUR ZU TESTZWECKEN AUF MEINER VM