version: '3'
services:
  login_patched:
    build:
      context: Login
    image: log4shell-login
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
    networks:
      - log4shell_patched
  
  httpserver_patched:
    build:
      context: HttpServer
    image: log4shell-httpserver
    hostname: hackerslabhttp_patched
    ports:
      - '8082:8082'
    networks:
      - log4shell_patched
  
  ldapserver_patched:
    build:
      context: LDAPServer
    image: log4shell-ldapserver
    hostname: hackerslabldap_patched
    ports:
      - '10389:10389'
    networks:
      - log4shell_patched

networks:
  log4shell_patched: