version: '3'
services:
    ubuntu_vulnapp:
        build: 
            context: ./ubuntu_vulnapp
        stdin_open: true
        tty: true
        ports:
            - 22:22
    
    database:
        build:
            context: ./db_init
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: users
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    login_vulnapp:
        build: 
            context: ./login_vulnapp 

    kali-client:
        build: ./Kali
        stdin_open: true
        tty: true
