services:
    ubuntu_vulnapp:
        build: 
            context: ./ubuntu_vulnapp
        stdin_open: true
        tty: true
        ports:
            - 22:22
    login_vulnapp:
        build: 
            context: ./login_vulnapp/db_init
    database:
        build:
            context: ./db_init
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: users
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        
    # kali-client:
    #     build: ./Kali
    #     stdin_open: true
    #     tty: true
    # database:
    #     image: mysql:8.0.27
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./web-server/v1/database/init:/docker-entrypoint-initdb.d/
