services:
    vulnapp:
        build: 
            context: ./web-server/v2
        ports:
            - 8080:80
    # kali-client:
    #     build: ./Kali
    #     stdin_open: true
    #     tty: true
    # database:
    #     image: mysql:8.0.27
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - ./web-server/v1/database/init:/docker-entrypoint-initdb.d/
