version: '3'
services:
  login:
    build:
      context: Login
    stdin_open: true
    tty: true
    command: ["tail", "-f", "/dev/null"]
    networks:
      - log4shell
  
  httpserver:
    build:
      context: HttpServer
    hostname: hackerslabhttp
    ports:
      - '8081:8081'
    networks:
      - log4shell
  
  ldapserver:
    build:
      context: LDAPServer
    hostname: hackerslabldap
    ports:
      - '1389:1389'
    networks:
      - log4shell

networks:
  log4shell: